---
# This is a sample database file for the Sequel ORM
:development: &defaults
  :adapter: postgres
  :database: sample1_development
  :username: morris
  :password: test
  :host: localhost
  #:socket: /tmp/mysql.sock

:test:
  :adapter: postgres
  :database: sample1_test
  :username: morris
  :password: test
  :host: localhost

:production:
  <<: *defaults
  :database: sample1_production